baseURL: 'https://michaelvaldron.ca/'
languageCode: en-us
title: Michael Valdron
module:
  imports:
    - path: github.com/luizdepra/hugo-coder
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  Name: Michael Valdron
  info: Software Engineer
  description: Michael Valdron's portfolio website
  keywords: 'developer,software,personal,portfolio'
  avatarurl: /img/self.jpg
  favicon_32: favicon.ico
  favicon_16: favicon.ico
  enableTwemoji: true
  colorScheme: dark
  hidecolorschemetoggle: false
  HeaderUsername: michael
  HeaderHostname: homepage
  ProfilePicture: /img/self.jpg
  BackgroundImage: /img/bg.png
  GithubID: michael-valdron
  LinkedInID: michael-valdron-3b8614a5
  BitbucketID: mvaldron/workspace/projects/PROJ
  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 1
      url: 'https://github.com/michael-valdron/'
    - name: Bitbucket
      icon: fa fa-bitbucket fa-2x
      weight: 2
      url: 'https://bitbucket.org/mvaldron/workspace/projects/PROJ'
    - name: LinkedIn
      icon: fa fa-linkedin fa-2x
      weight: 3
      url: 'https://www.linkedin.com/in/michael-valdron-3b8614a5/'
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects
      weight: 1
    - identifier: publications
      name: Publications
      url: /publications
      weight: 2
    - identifier: interests
      name: Interests
      url: /interests
      weight: 3
